/**
 * Títulos curtos usados antes de a tradução completa do módulo ser carregada.
 * Mantém a primeira Ribbon idêntica à versão eager sem trazer todo o texto de
 * 37 módulos para o caminho crítico do boot.
 */
const MODULE_TITLES: Record<string, Record<string, string>> = {
  pt: {
    album: "Álbum",
    animation: "Animação",
    announcements: "Anúncios",
    background_projection: "Projeção de Fundo",
    background_sound: "Som de Fundo",
    base_module: "Título do Módulo",
    bible: "Bíblia",
    bible_search: "Busca Bíblica",
    children: "Infantil",
    clock: "Relógio",
    collections: "Coletâneas Diversas",
    counter: "Contador",
    custom_collections: "Coletâneas Personalizadas",
    custom_online_videos: "Meus Vídeos Online",
    doxology: "Doxologia",
    draw: "Sorteio",
    favorites: "Favoritos",
    history: "Histórico",
    hymnal: "Hinário Adventista",
    hymnal_1996: "Hinário 1996",
    libras: "Libras",
    liturgy: "Liturgia",
    lyric: "Letra",
    media: "Slide",
    media_library: "Biblioteca de Mídia",
    message_board: "Painel de Recados",
    musics: "Músicas",
    name_draw: "Sorteio de Nomes",
    online_videos: "Vídeos On-line",
    overlay: "Sobreposições",
    remote_control: "Controle Remoto",
    scheduled_items: "Itens Agendados",
    slide_editor: "Editor de Músicas",
    stopwatch: "Cronômetro",
    theme: "Aparência",
    timer: "Temporizador",
    timer_worship: "Temporizador de Culto",
  },
  es: {
    album: "Álbum",
    animation: "Animaciones",
    announcements: "Anuncios",
    background_projection: "Proyección de Fondo",
    background_sound: "Sonido de Fondo",
    base_module: "Título del módulo",
    bible: "Biblia",
    bible_search: "Búsqueda Bíblica",
    children: "Infantil",
    clock: "Reloj",
    collections: "Colecciones Diversas",
    counter: "Contador",
    custom_collections: "Colecciones Personales",
    custom_online_videos: "Mis Videos en Línea",
    doxology: "Doxología",
    draw: "Sorteo",
    favorites: "Favoritos",
    history: "Historial",
    hymnal: "Himnario Adventista",
    hymnal_1996: "Himnario 1996",
    libras: "Libras",
    liturgy: "Liturgia",
    lyric: "Letra",
    media: "Diapositiva",
    media_library: "Biblioteca de Medios",
    message_board: "Panel de Avisos",
    musics: "Músicas",
    name_draw: "Sorteo de Nombres",
    online_videos: "Vídeos En línea",
    overlay: "Superposiciones",
    remote_control: "Control Remoto",
    scheduled_items: "Ítems Agendados",
    slide_editor: "Editor de Música",
    stopwatch: "Cronómetro",
    theme: "Apariencia",
    timer: "Temporizador de culto",
    timer_worship: "Temporizador de Culto",
  },
};

export function moduleTitleFallback(
  locale: string,
  moduleId: string,
  manifestName?: string
): string {
  return MODULE_TITLES[locale]?.[moduleId] || manifestName || moduleId;
}
