export enum ModuleGroupEnum {
  ALBUMS = "albums",
  BIBLE_GENERAL = "bible_general",
  CATEGORIES = "categories",
  CHURCH = "church",
  DRAWS = "draws",
  FAVORITES_LIST = "favorites_list",
  HYMNAL = "hymnal",
  MEDIA = "media",
  ONLINE_VIDEOS = "online_videos",
  REMOTE = "remote",
  TEXTS = "texts",
  THEME = "theme",
  TIME = "time",
  USER = "user",
}
