/**
 * ID do Módulo deve ser em snake_case
 */
export enum ModuleEnum {
  ALBUM = "album",
  ANIMATION = "animation",
  ANNOUNCEMENTS = "announcements",
  BACKGROUND_SOUND = "background_sound",
  BACKGROUND_PROJECTION = "background_projection",
  BASE_MODULE = "base_module",
  BIBLE = "bible",
  BIBLE_SEARCH = "bible_search",
  CHILDREN = "children",
  CLOCK = "clock",
  COLLECTIONS = "collections",
  COUNTER = "counter",
  CUSTOM_COLLECTIONS = "custom_collections",
  CUSTOM_ONLINE_VIDEOS = "custom_online_videos",
  DRAW = "draw",
  DOXOLOGY = "doxology",
  FAVORITES = "favorites",
  HISTORY = "history",
  HYMNAL = "hymnal",
  HYMNAL_1996 = "hymnal_1996",
  LITURGY = "liturgy",
  LYRIC = "lyric",
  MEDIA = "media",
  MEDIA_LIBRARY = "media_library",
  MESSAGE_BOARD = "message_board",
  MUSICS = "musics",
  NAME_DRAW = "name_draw",
  ONLINE_VIDEOS = "online_videos",
  OVERLAY = "overlay",
  REMOTE_CONTROL = "remote_control",
  SCHEDULED_ITEMS = "scheduled_items",
  SLIDE_EDITOR = "slide_editor",
  STOPWATCH = "stopwatch",
  THEME = "theme",
  TIMER = "timer",
  TIMER_WORSHIP = "timer_worship",
  LIBRAS = "libras",
}
