import type { FunctionalComponent, SVGAttributes } from "vue";
import {
  IconAccessible,
  IconAdjustmentsHorizontal,
  IconAlarm,
  IconAlbum,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangleFilled,
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconApi,
  IconArrowBackUp,
  IconArrowBarRight,
  IconArrowBigLeft,
  IconArrowBigRight,
  IconArrowDown,
  IconArrowDownLeft,
  IconArrowDownRight,
  IconArrowForwardUp,
  IconArrowLeft,
  IconArrowMerge,
  IconArrowsExchange,
  IconArrowsShuffle,
  IconAspectRatio,
  IconAtom,
  IconBell,
  IconBellOff,
  IconBible,
  IconBrandAndroid,
  IconBrandApple,
  IconBlur,
  IconBolt,
  IconBook,
  IconBook2,
  IconBookmarkFilled,
  IconBooks,
  IconBraces,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandWhatsapp,
  IconBrandX,
  IconBrandYoutube,
  IconBucketDroplet,
  IconBug,
  IconBuildingChurch,
  IconCalendar,
  IconCalendarCheck,
  IconCalendarClock,
  IconCalendarFilled,
  IconCalendarStar,
  IconCalendarWeek,
  IconCamera,
  IconCameraFilled,
  IconCandle,
  IconCaretDownFilled,
  IconCaretLeftFilled,
  IconCast,
  IconChalkboard,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronLeftPipe,
  IconChevronRight,
  IconChevronRightPipe,
  IconChevronUp,
  IconCircle,
  IconCircleArrowDownFilled,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleDot,
  IconCirclePlus,
  IconCircleXFilled,
  IconClearAll,
  IconClef,
  IconClock,
  IconClock24,
  IconClockPlay,
  IconClockStop,
  IconCloudDataConnection,
  IconCloudDownload,
  IconCodeDots,
  IconConfetti,
  IconCopy,
  IconCopyCheck,
  IconCopyPlus,
  IconCursorText,
  IconDatabase,
  IconDatabaseImport,
  IconDatabaseMinus,
  IconDeviceDesktop,
  IconDeviceDesktopAnalytics,
  IconDeviceDesktopDown,
  IconDeviceDesktopOff,
  IconDeviceFloppy,
  IconDeviceImac,
  IconDeviceRemote,
  IconDeviceSpeaker,
  IconDeviceTv,
  IconDevices,
  IconDice,
  IconDice5,
  IconDisc,
  IconDiscFilled,
  IconDoorExit,
  IconDotsVertical,
  IconDownload,
  IconEraser,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileExport,
  IconFileImport,
  IconFileMusic,
  IconFileMusicFilled,
  IconFilePencil,
  IconFilePlus,
  IconFileSearch,
  IconFileSettings,
  IconFileText,
  IconFileTypePdf,
  IconFiles,
  IconFilter,
  IconFolder,
  IconFolderHeart,
  IconFolderOff,
  IconFolderOpen,
  IconFolderSearch,
  IconFolders,
  IconGripVertical,
  IconHandLoveYou,
  IconHandOff,
  IconHandTwoFingers,
  IconHeartHandshake,
  IconHelpCircle,
  IconHighlight,
  IconHistory,
  IconHourglass,
  IconHourglassLow,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconKeyboard,
  IconKeyframes,
  IconLanguage,
  IconLayersOff,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLayoutGridFilled,
  IconLeaf,
  IconLibrary,
  IconLibraryPhoto,
  IconLineHeight,
  IconLink,
  IconList,
  IconListCheck,
  IconListNumbers,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMailFilled,
  IconMan,
  IconMaximize,
  IconMenu2,
  IconMessage2,
  IconMessageReport,
  IconMicrophone2,
  IconMinimize,
  IconMinus,
  IconMoodHappy,
  IconMoodSad,
  IconMoon,
  IconMovie,
  IconMusic,
  IconMusicOff,
  IconMusicPlus,
  IconNetwork,
  IconNews,
  IconNotes,
  IconNumber123,
  IconPalette,
  IconPaletteFilled,
  IconPencil,
  IconPencilFilled,
  IconPhoto,
  IconPhotoEdit,
  IconPhotoMinus,
  IconPhotoOff,
  IconPhotoPlus,
  IconPiano,
  IconPilcrow,
  IconPin,
  IconPinnedOff,
  IconPlayerPauseFilled,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconPlaylist,
  IconPlaylistAdd,
  IconPlaylistFilled,
  IconPlaylistX,
  IconPlugOff,
  IconPlus,
  IconPointFilled,
  IconPower,
  IconPresentation,
  IconPresentationFilled,
  IconProgressDown,
  IconPuzzle,
  IconQrcode,
  IconQuote,
  IconRefresh,
  IconRepeat,
  IconRepeatOff,
  IconRestore,
  IconRewindBackward10,
  IconRewindForward10,
  IconRotateClockwise,
  IconScreenShare,
  IconScript,
  IconSearch,
  IconSectionSign,
  IconSend,
  IconSeparatorHorizontal,
  IconServer,
  IconSettings,
  IconSettingsFilled,
  IconSlideshow,
  IconSpeakerphone,
  IconSquare,
  IconSquareCheckFilled,
  IconSquareMinus,
  IconSquarePlus,
  IconSquares,
  IconStack2,
  IconStack3,
  IconStar,
  IconStarFilled,
  IconStarOff,
  IconStopwatch,
  IconSun,
  IconSunMoon,
  IconTag,
  IconTerminal2,
  IconTools,
  IconTransfer,
  IconTransitionRight,
  IconTrash,
  IconTrashFilled,
  IconTrophy,
  IconUpload,
  IconUser,
  IconUserHeart,
  IconUserShield,
  IconUsers,
  IconVideo,
  IconVideoFilled,
  IconVideoPlus,
  IconVinyl,
  IconVolume,
  IconVolume2,
  IconVolume3,
  IconVolume4,
  IconWallpaper,
  IconWallpaperOff,
  IconWifi,
  IconWifiOff,
  IconWindowMaximize,
  IconWorld,
  IconX,
  IconYoga,
} from "@tabler/icons-vue";

/**
 * Registro dos ícones de interface do Tabler.
 *
 * O desenho vem do pacote `@tabler/icons-vue`, não de arquivo no repositório:
 * acervo copiado congela na versão do dia da cópia e convida cada um a soltar
 * o próprio SVG ao lado. Só as marcas do projeto — que o Tabler não tem — seguem
 * como arquivo, em `src/assets/icons/`.
 *
 * Os imports são nomeados de propósito. Resolver por nome a partir de
 * `import * as` arrastaria os 6250 ícones do pacote para o bundle; assim entra
 * só o que está listado aqui.
 *
 * Ícone novo entra em três passos: a constante em `ICONS.*`, o import e a
 * entrada abaixo. `Icons.spec.ts` falha enquanto faltar qualquer um.
 */
export const TABLER_ICONS: Record<string, FunctionalComponent<SVGAttributes>> = {
  accessible: IconAccessible,
  "adjustments-horizontal": IconAdjustmentsHorizontal,
  alarm: IconAlarm,
  album: IconAlbum,
  "alert-circle": IconAlertCircle,
  "alert-circle-filled": IconAlertCircleFilled,
  "alert-triangle-filled": IconAlertTriangleFilled,
  "align-center": IconAlignCenter,
  "align-left": IconAlignLeft,
  "align-right": IconAlignRight,
  api: IconApi,
  "arrow-back-up": IconArrowBackUp,
  "arrow-bar-right": IconArrowBarRight,
  "arrow-big-left": IconArrowBigLeft,
  "arrow-big-right": IconArrowBigRight,
  "arrow-down": IconArrowDown,
  "arrow-down-left": IconArrowDownLeft,
  "arrow-down-right": IconArrowDownRight,
  "arrow-forward-up": IconArrowForwardUp,
  "arrow-left": IconArrowLeft,
  "arrow-merge": IconArrowMerge,
  "arrows-exchange": IconArrowsExchange,
  "arrows-shuffle": IconArrowsShuffle,
  "aspect-ratio": IconAspectRatio,
  atom: IconAtom,
  bell: IconBell,
  "bell-off": IconBellOff,
  bible: IconBible,
  "brand-android": IconBrandAndroid,
  "brand-apple": IconBrandApple,
  blur: IconBlur,
  bolt: IconBolt,
  book: IconBook,
  "book-2": IconBook2,
  "bookmark-filled": IconBookmarkFilled,
  books: IconBooks,
  braces: IconBraces,
  "brand-facebook": IconBrandFacebook,
  "brand-github": IconBrandGithub,
  "brand-instagram": IconBrandInstagram,
  "brand-linkedin": IconBrandLinkedin,
  "brand-whatsapp": IconBrandWhatsapp,
  "brand-x": IconBrandX,
  "brand-youtube": IconBrandYoutube,
  "bucket-droplet": IconBucketDroplet,
  bug: IconBug,
  "building-church": IconBuildingChurch,
  calendar: IconCalendar,
  "calendar-check": IconCalendarCheck,
  "calendar-clock": IconCalendarClock,
  "calendar-filled": IconCalendarFilled,
  "calendar-star": IconCalendarStar,
  "calendar-week": IconCalendarWeek,
  camera: IconCamera,
  "camera-filled": IconCameraFilled,
  candle: IconCandle,
  "caret-down-filled": IconCaretDownFilled,
  "caret-left-filled": IconCaretLeftFilled,
  cast: IconCast,
  chalkboard: IconChalkboard,
  "chart-bar": IconChartBar,
  check: IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-left-pipe": IconChevronLeftPipe,
  "chevron-right": IconChevronRight,
  "chevron-right-pipe": IconChevronRightPipe,
  "chevron-up": IconChevronUp,
  circle: IconCircle,
  "circle-arrow-down-filled": IconCircleArrowDownFilled,
  "circle-check": IconCircleCheck,
  "circle-check-filled": IconCircleCheckFilled,
  "circle-dot": IconCircleDot,
  "circle-plus": IconCirclePlus,
  "circle-x-filled": IconCircleXFilled,
  "clear-all": IconClearAll,
  clef: IconClef,
  clock: IconClock,
  "clock-24": IconClock24,
  "clock-play": IconClockPlay,
  "clock-stop": IconClockStop,
  "cloud-data-connection": IconCloudDataConnection,
  "cloud-download": IconCloudDownload,
  "code-dots": IconCodeDots,
  confetti: IconConfetti,
  copy: IconCopy,
  "copy-check": IconCopyCheck,
  "copy-plus": IconCopyPlus,
  "cursor-text": IconCursorText,
  database: IconDatabase,
  "database-import": IconDatabaseImport,
  "database-minus": IconDatabaseMinus,
  "device-desktop": IconDeviceDesktop,
  "device-desktop-analytics": IconDeviceDesktopAnalytics,
  "device-desktop-down": IconDeviceDesktopDown,
  "device-desktop-off": IconDeviceDesktopOff,
  "device-floppy": IconDeviceFloppy,
  "device-imac": IconDeviceImac,
  "device-remote": IconDeviceRemote,
  "device-speaker": IconDeviceSpeaker,
  "device-tv": IconDeviceTv,
  devices: IconDevices,
  dice: IconDice,
  "dice-5": IconDice5,
  disc: IconDisc,
  "disc-filled": IconDiscFilled,
  "door-exit": IconDoorExit,
  "dots-vertical": IconDotsVertical,
  download: IconDownload,
  eraser: IconEraser,
  "external-link": IconExternalLink,
  eye: IconEye,
  "eye-off": IconEyeOff,
  file: IconFile,
  "file-export": IconFileExport,
  "file-import": IconFileImport,
  "file-music": IconFileMusic,
  "file-music-filled": IconFileMusicFilled,
  "file-pencil": IconFilePencil,
  "file-plus": IconFilePlus,
  "file-search": IconFileSearch,
  "file-settings": IconFileSettings,
  "file-text": IconFileText,
  "file-type-pdf": IconFileTypePdf,
  files: IconFiles,
  filter: IconFilter,
  folder: IconFolder,
  "folder-heart": IconFolderHeart,
  "folder-off": IconFolderOff,
  "folder-open": IconFolderOpen,
  "folder-search": IconFolderSearch,
  folders: IconFolders,
  "grip-vertical": IconGripVertical,
  "hand-love-you": IconHandLoveYou,
  "hand-off": IconHandOff,
  "hand-two-fingers": IconHandTwoFingers,
  "heart-handshake": IconHeartHandshake,
  "help-circle": IconHelpCircle,
  highlight: IconHighlight,
  history: IconHistory,
  hourglass: IconHourglass,
  "hourglass-low": IconHourglassLow,
  "info-circle": IconInfoCircle,
  "info-circle-filled": IconInfoCircleFilled,
  keyboard: IconKeyboard,
  keyframes: IconKeyframes,
  language: IconLanguage,
  "layers-off": IconLayersOff,
  "layout-dashboard": IconLayoutDashboard,
  "layout-grid": IconLayoutGrid,
  "layout-grid-filled": IconLayoutGridFilled,
  leaf: IconLeaf,
  library: IconLibrary,
  "library-photo": IconLibraryPhoto,
  "line-height": IconLineHeight,
  link: IconLink,
  list: IconList,
  "list-check": IconListCheck,
  "list-numbers": IconListNumbers,
  lock: IconLock,
  "lock-open": IconLockOpen,
  mail: IconMail,
  "mail-filled": IconMailFilled,
  man: IconMan,
  maximize: IconMaximize,
  "menu-2": IconMenu2,
  "message-2": IconMessage2,
  "message-report": IconMessageReport,
  "microphone-2": IconMicrophone2,
  minimize: IconMinimize,
  minus: IconMinus,
  "mood-happy": IconMoodHappy,
  "mood-sad": IconMoodSad,
  moon: IconMoon,
  movie: IconMovie,
  music: IconMusic,
  "music-off": IconMusicOff,
  "music-plus": IconMusicPlus,
  network: IconNetwork,
  news: IconNews,
  notes: IconNotes,
  "number-123": IconNumber123,
  palette: IconPalette,
  "palette-filled": IconPaletteFilled,
  pencil: IconPencil,
  "pencil-filled": IconPencilFilled,
  photo: IconPhoto,
  "photo-edit": IconPhotoEdit,
  "photo-minus": IconPhotoMinus,
  "photo-off": IconPhotoOff,
  "photo-plus": IconPhotoPlus,
  piano: IconPiano,
  pilcrow: IconPilcrow,
  pin: IconPin,
  "pinned-off": IconPinnedOff,
  "player-pause-filled": IconPlayerPauseFilled,
  "player-play": IconPlayerPlay,
  "player-play-filled": IconPlayerPlayFilled,
  "player-skip-back": IconPlayerSkipBack,
  "player-skip-forward": IconPlayerSkipForward,
  "player-stop": IconPlayerStop,
  "player-stop-filled": IconPlayerStopFilled,
  "player-track-next": IconPlayerTrackNext,
  "player-track-prev": IconPlayerTrackPrev,
  playlist: IconPlaylist,
  "playlist-add": IconPlaylistAdd,
  "playlist-filled": IconPlaylistFilled,
  "playlist-x": IconPlaylistX,
  "plug-off": IconPlugOff,
  plus: IconPlus,
  "point-filled": IconPointFilled,
  power: IconPower,
  presentation: IconPresentation,
  "presentation-filled": IconPresentationFilled,
  "progress-down": IconProgressDown,
  puzzle: IconPuzzle,
  qrcode: IconQrcode,
  quote: IconQuote,
  refresh: IconRefresh,
  repeat: IconRepeat,
  "repeat-off": IconRepeatOff,
  restore: IconRestore,
  "rewind-backward-10": IconRewindBackward10,
  "rewind-forward-10": IconRewindForward10,
  "rotate-clockwise": IconRotateClockwise,
  "screen-share": IconScreenShare,
  script: IconScript,
  search: IconSearch,
  "section-sign": IconSectionSign,
  send: IconSend,
  "separator-horizontal": IconSeparatorHorizontal,
  server: IconServer,
  settings: IconSettings,
  "settings-filled": IconSettingsFilled,
  slideshow: IconSlideshow,
  speakerphone: IconSpeakerphone,
  square: IconSquare,
  "square-check-filled": IconSquareCheckFilled,
  "square-minus": IconSquareMinus,
  "square-plus": IconSquarePlus,
  squares: IconSquares,
  "stack-2": IconStack2,
  "stack-3": IconStack3,
  star: IconStar,
  "star-filled": IconStarFilled,
  "star-off": IconStarOff,
  stopwatch: IconStopwatch,
  sun: IconSun,
  "sun-moon": IconSunMoon,
  tag: IconTag,
  "terminal-2": IconTerminal2,
  tools: IconTools,
  transfer: IconTransfer,
  "transition-right": IconTransitionRight,
  trash: IconTrash,
  "trash-filled": IconTrashFilled,
  trophy: IconTrophy,
  upload: IconUpload,
  user: IconUser,
  "user-heart": IconUserHeart,
  "user-shield": IconUserShield,
  users: IconUsers,
  video: IconVideo,
  "video-filled": IconVideoFilled,
  "video-plus": IconVideoPlus,
  vinyl: IconVinyl,
  volume: IconVolume,
  "volume-2": IconVolume2,
  "volume-3": IconVolume3,
  "volume-4": IconVolume4,
  wallpaper: IconWallpaper,
  "wallpaper-off": IconWallpaperOff,
  wifi: IconWifi,
  "wifi-off": IconWifiOff,
  "window-maximize": IconWindowMaximize,
  world: IconWorld,
  x: IconX,
  yoga: IconYoga,
};

export const ICONS = {
  /**
   * Ícones do Material Design Icons (https://materialdesignicons.com/))
   */
  ACTIONS: {
    ADD: "plus",
    ADD_BOX: "square-plus",
    ADD_CIRCLE: "circle-plus",
    CANCEL: "circle-x-filled",
    CHECK_CIRCLE: "circle-check",
    CLEAN: "eraser",
    CLOSE: "x",
    CLOUD_DOWNLOAD: "cloud-download",
    COPY: "copy",
    DATABASE_REFRESH: "database-import",
    DATABASE_REMOVE: "database-minus",
    DELETE: "trash",
    DELETE_FILLED: "trash-filled",
    DOWNLOAD: "download",
    DOWNLOAD_OUTLINE: "download",
    DRAG: "grip-vertical",
    DUPLICATE: "copy-plus",
    EDIT: "pencil-filled",
    EDIT_OUTLINE: "pencil",
    EXPAND_RIGHT: "arrow-bar-right",
    EXPORT: "file-export",
    EXPORT_FILE: "file-export",
    FILE_IMPORT: "file-import",
    FILE_SETTINGS: "file-settings",
    FILTER: "filter",
    FOLDER_OPEN: "folder-open",
    FOLDER_SYNC: "folder-search",
    FORMAT: "highlight",
    IMAGE_EDIT: "photo-edit",
    IMAGE_PLUS: "photo-plus",
    IMAGE_PLUS_OUTLINE: "photo-plus",
    IMAGE_REMOVE: "photo-minus",
    IMPORT: "file-import",
    LOCK: "lock",
    LOCK_OPEN: "lock-open",
    MINUS: "minus",
    MINUS_BOX: "square-minus",
    NEXT: "chevron-right",
    NEXT_BOLD: "arrow-big-right",
    PREVIOUS: "chevron-left",
    PREVIOUS_BOLD: "arrow-big-left",
    redo: "arrow-forward-up",
    REFRESH: "refresh",
    RENAME: "cursor-text",
    RESTART: "rotate-clockwise",
    RESTORE: "restore",
    SAVE: "device-floppy",
    SAVE_EDIT: "file-pencil",
    SEARCH: "search",
    SELECT_MULTIPLE: "copy-check",
    SORT: "arrows-exchange",
    SPLIT: "separator-horizontal",
    START: "power",
    STOP: "plug-off",
    UNCHECKED: "square",
    UNDO: "arrow-back-up",
    UPLOAD: "upload",
  },
  BIBLE: {
    BIBLE: "bible",
    BOOK_BIBLE: "bible",
    BOOK_OPEN: "book",
    BOOK_OPEN_PAGE: "book-2",
    BOOK_SEARCH: "file-search",
    BOOKMARK: "bookmark-filled",
    FORMAT_PARAGRAPH: "pilcrow",
    FORMAT_QUOTE_CLOSE: "quote",
    FORMAT_SECTION: "section-sign",
    TEXT_BOX_OUTLINE: "file-text",
  },
  CALENDAR: {
    BLANK: "calendar",
    BLANK_SOLID: "calendar-filled",
    CLOCK: "calendar-clock",
    HECK: "calendar-check",
    MULTISELECT: "calendar-week",
    STAR: "calendar-star",
  },
  CATEGORY: {
    MUSIC: "music-plus",
    ACTION: "bolt",
    WORSHIP: "building-church",
    APPEAL: "user-heart",
    HAPPY: "mood-happy",
    SAD: "mood-sad",
    SUSPENSE: "alert-circle",
    CELEBRATION: "confetti",
    PEACE: "sun",
    MEDITATION: "yoga",
    NATURE: "leaf",
    SOLEMN: "candle",
    URGENT: "alert-triangle-filled",
    VICTORY: "trophy",
    THANKSGIVING: "hand-two-fingers",
    INTRO: "player-play",
    CLOSING: "player-stop",
    JA: "ja",
  },
  FORMAT: {
    ALIGN_CENTER: "align-center",
    ALIGN_LEFT: "align-left",
    ALIGN_RIGHT: "align-right",
    ASPECT_RATIO: "aspect-ratio",
    COLOR_FILL: "bucket-droplet",
    LINE_SPACING: "line-height",
    LIST_BULLETED: "list",
    LIST_NUMBERED: "list-numbers",
    PALETTE: "palette-filled",
    PALETTE_OUTLINE: "palette",
    PARAGRAPH: "pilcrow",
  },
  LITURGY: {
    BOOKSHELF: "books",
    BULLETIN_BOARD: "chalkboard",
    REMOTE: "device-remote",
    SCRIPT: "script",
  },
  MEDIA: {
    ADD: "music-plus",
    AUDIO: "music",
    AUDIO_PLAYER: "vinyl",
    AUDIO_VIDEO: "device-speaker",
    BLUR: "blur",
    CAMERA: "camera-filled",
    CAMERA_OUTLINE: "camera",
    CINEMA: "movie",
    CINEMA_OUTLINE: "movie",
    COMPUTER: "device-imac",
    DISC: "disc",
    EQUALIZER: "chart-bar",
    IMAGE: "photo",
    IMAGE_MULTIPLE: "library-photo",
    IMAGE_MULTIPLE_OUTLINE: "library-photo",
    LIBRARY: "library",
    PLAYLIST: "playlist",
    TELEVISION_PLAY: "screen-share",
    VIDEO: "video",
    VIDEO_FILE: "video-filled",
    YOUTUBE: "brand-youtube",
  },
  MODULES: {
    ALBUM: "library",
    ANIMATION: "keyframes",
    ANNOUNCEMENTS: "speakerphone",
    BACKGROUND_PROJECTION: "wallpaper",
    BACKGROUND_SOUND: "vinyl",
    BASE_MODULE: "device-desktop-analytics",
    BIBLE: "book",
    BIBLE_SEARCH: "file-search",
    CLOCK: "clock",
    COLLECTIONS: "nt",
    COUNTER: "number-123",
    CUSTOM_COLLECTONS: "playlist",
    CUSTOM_MUSICS: "playlist",
    CUSTOM_ONLINE_VIDEOS: "video-plus",
    DOXOLOGY: "church",
    DRAW: "dice",
    FAVORITES: "star-filled",
    HISTORY: "history",
    HYMNAL: "hasd",
    HYMNAL_1996: "hasd",
    INTERACTIVE_TEXT: "quote",
    KIDS: "kids",
    LIBRAS: "hand-love-you",
    LITURGY: "liturgy",
    MEDIA: "file-music-filled",
    MEDIA_LIBRARY: "movie",
    MESSAGE_BOARD: "message-2",
    MUSIC_SEARCH: "search",
    MUSICS: "ja",
    NAME_DRAW: "users",
    ONLINE_VIDEOS: "brand-youtube",
    OVERLAY: "stack-2",
    REMOTE_CONTROL: "device-remote",
    SCHEDULED_ITEMS: "calendar-check",
    SLIDE_EDITOR: "slideshow",
    STOPWATCH: "stopwatch",
    THEME: "palette-filled",
    TIMER: "hourglass",
    TIMER_WORSHIP: "hourglass-low",
  },
  CHAT: {
    SEND: "send",
  },
  MUSIC: {
    ALBUM: "album",
    AUDIO: "file-music-filled",
    AUDIO_PLAYBACK: "file-music",
    CLEF: "clef",
    FILE: "file-music",
    FOLDER: "folder",
    LYRIC: "file-text",
    MICROPHONE: "microphone-2",
    MUSIC: "music",
    NOTE: "music",
    NOTE_EIGHTH: "music",
    NOTE_OUTLINE: "music",
    NO_AUDIO: "music-off",
    OFF: "music-off",
    PIANO: "piano",
    PLAYBACK: "disc",
    PLAYBACK_MULTIPLE: "disc",
    SING: "disc-filled",
    SLIDES_AUDIO: "slideshow",
    SLIDES_ONLY: "squares",
    SLIDES_PLAYBACK: "presentation",
    SUNG: "disc-filled",
    VINYL: "vinyl",
  },
  PLAYER: {
    FAST_FORWARD: "player-track-next",
    FORWARD_10: "rewind-forward-10",
    FULLSCREEN: "maximize",
    FULLSCREEN_EXIT: "minimize",
    LOOP: "repeat",
    LOOP_OFF: "repeat-off",
    NEXT: "player-skip-forward",
    PAGE_FIRST: "chevron-left-pipe",
    PAGE_LAST: "chevron-right-pipe",
    PAUSE: "player-pause-filled",
    /** Pausa sem círculo — par de PLAYER; usado no player do rodapé. */
    PAUSE_PLAIN: "player-pause-filled",
    PLAY: "player-play-filled",
    PLAYER: "player-play-filled",
    PLAYLIST: "playlist-filled",
    PLAYLIST_CHECK: "list-check",
    PLAYLIST_PLUS: "playlist-add",
    PLAYLIST_REMOVE: "playlist-x",
    PLAY_OUTLINE: "player-play",
    PLAY_PAUSE: "player-play",
    PREV: "player-skip-back",
    RECORD: "circle-dot",
    REPEAT: "restore",
    REWIND: "player-track-prev",
    REWIND_10: "rewind-backward-10",
    SHUFFLE: "arrows-shuffle",
    SKIP_BACKWARD: "player-skip-back",
    SKIP_FORWARD: "player-skip-forward",
    STOP: "player-stop",
    STOP_CIRCLE: "player-stop-filled",
    TRANSITION: "transition-right",
    VOLUME_HIGH: "volume",
    VOLUME_LOW: "volume-4",
    VOLUME_MEDIUM: "volume-2",
    VOLUME_MUTE: "volume-3",
  },
  PROJECTION: {
    CLEAN: "wallpaper-off",
    PRESENT: "slideshow",
    PRESENTATION: "presentation",
    RETURN: "screen-share",
    SCREEN: "presentation-filled",
    SCREEN_OUTLINE: "presentation",
    START: "device-desktop",
    STOP: "device-desktop-off",
    TELEVISION: "device-tv",
  },
  SORT: {
    DICE: "dice-5",
    SORTER: "dice",
  },
  TIMER: {
    ALARM: "alarm",
    CALL_MERGE: "arrow-merge",
    CLOCK: "clock",
    CLOCK_END: "clock-stop",
    CLOCK_START: "clock-play",
    COUNTER: "number-123",
    HOURS_24: "clock-24",
    STOPWATCH: "stopwatch",
    TIMER: "stopwatch",
    TIMER_OUTLINE: "stopwatch",
    TIMER_SAND: "hourglass",
  },
  UI: {
    ACCESSIBILITY: "accessible",
    ACCOUNT: "user",
    ALERT: "alert-triangle-filled",
    ALERT_CIRCLE: "alert-circle-filled",
    ANDROID: "brand-android",
    APPLE: "brand-apple",
    ARROW_BOTTOM_LEFT: "arrow-down-left",
    ARROW_BOTTOM_RIGHT: "arrow-down-right",
    ARROW_DOWN: "arrow-down",
    ARROW_LEFT: "arrow-left",
    AVATAR: "man",
    BACK: "chevron-left",
    BELL: "bell",
    BELL_OFF: "bell-off",
    BROOM: "clear-all",
    BUG: "bug",
    CHECK: "check",
    CHECKED: "square-check-filled",
    CHECK_CIRCLE: "circle-check-filled",
    CHECK_UPDATE: "device-desktop-down",
    CHEVRON_DOWN: "chevron-down",
    CHEVRON_RIGHT: "chevron-right",
    CHEVRON_UP: "chevron-up",
    CIRCLE_OUTLINE: "circle",
    CODE_BRACES: "braces",
    CONSOLE: "terminal-2",
    DASHBOARD: "layout-dashboard",
    DATABASE: "database",
    DEV: "code-dots",
    DONATE: "heart-handshake",
    DOT: "point-filled",
    DOTS_VERTICAL: "dots-vertical",
    DOT_SMALL: "point-filled",
    DOWNLOAD_CIRCLE: "circle-arrow-down-filled",
    ERASER: "eraser",
    EYE: "eye",
    EYE_OFF: "eye-off",
    EYE_OUTLINE: "eye",
    EXIT: "door-exit",
    FEEDBACK: "message-report",
    FILE: "file",
    FILE_MULTIPLE: "files",
    FILE_PDF: "file-type-pdf",
    FILE_PLUS: "file-plus",
    FOLDER: "folder",
    FOLDER_HEART: "folder-heart",
    FOLDER_MULTIPLE: "folders",
    FOLDER_OFF: "folder-off",
    FOLDER_OPEN: "folder-open",
    GRID_LARGE: "layout-grid",
    HARDDISK: "server",
    HELP: "help-circle",
    HISTORY: "history",
    IMAGE_OFF: "photo-off",
    IMAGE_OUTLINE: "photo",
    IMPORT_EXPORT: "transfer",
    INFORMATION_OUTLINE: "info-circle",
    INFO_SOLID: "info-circle-filled",
    INSTALL: "device-desktop-down",
    IP_NETWORK: "network",
    KEYBOARD: "keyboard",
    LAYERS: "stack-3",
    LAYERS_OFF: "layers-off",
    LIBRAS_OFF: "hand-off",
    LIBRAS_ON: "hand-love-you",
    LINK: "link",
    LINK_VARIANT: "link",
    MENU: "menu-2",
    MENU_DOWN: "caret-down-filled",
    MENU_LEFT: "caret-left-filled",
    MESSAGE_BULLETED: "message-2",
    MONITOR: "device-desktop",
    MONITORS: "devices",
    NEWS: "news",
    NOTE_EDIT: "file-pencil",
    NOTE_TEXT: "notes",
    NOTE_TEXT_OUTLINE: "notes",
    OPEN_IN_APP: "window-maximize",
    OPEN_IN_NEW: "external-link",
    OPTIONS: "settings-filled",
    OPTIONS_OUTLINE: "settings",
    PIN: "pin",
    PIN_OFF: "pinned-off",
    PLAYER: "music",
    PRIVACY: "user-shield",
    PROGRESS_DOWNLOAD: "progress-down",
    PUZZLE: "puzzle",
    QRCODE: "qrcode",
    SERVER: "server",
    STAR: "star-filled",
    STAR_OFF: "star-off",
    STAR_OFF_OUTLINE: "star-off",
    STAR_OUTLINE: "star",
    SYNC: "refresh",
    SYNC_CLOUD: "cloud-data-connection",
    TAG: "tag",
    THEME_DARK: "moon",
    THEME_LIGHT: "sun",
    THEME_LIGHT_DARK: "sun-moon",
    TOOLS: "tools",
    TRANSLATE: "language",
    TUNE: "adjustments-horizontal",
    VIEW_GRID: "layout-grid-filled",
    VIEW_GRID_OUTLINE: "layout-grid",
    VIEW_LIST: "list",
    WEB: "world",
    WIFI: "wifi",
    WIFI_OFF: "wifi-off",
    WINDOW_MAXIMIZE: "square",
    WINDOW_MINIMIZE: "minus",
    WINDOW_RESTORE: "squares",
  },
  /**
   * Contato e redes sociais (links da tela Sobre)
   */
  SOCIAL: {
    CAST: "cast",
    EMAIL: "mail-filled",
    EMAIL_OUTLINE: "mail",
    FACEBOOK: "brand-facebook",
    GITHUB: "brand-github",
    INSTAGRAM: "brand-instagram",
    LINKEDIN: "brand-linkedin",
    TELEGRAM: "send",
    WHATSAPP: "brand-whatsapp",
    X: "brand-x",
  },
  PROJETOS: {
    WEB: "world",
    ELECTRON: "atom",
    DELPHI: "device-imac",
    API: "api",
  },
  /**
   * Ícones SVG  da pasta /assets/icons usados no componente Icon
   */
  CUSTOM: {
    AVT: "avt",
    AVT_COLOR: "avt-color",
    CHURCH: "church",
    DBV: "dbv",
    DBV_COLOR: "dbv-color",
    DBV_ALT: "dbv-alt",
    DBV_ALT_COLOR: "dbv-alt-color",
    HASD: "hasd",
    IASD: "iasd",
    IASD_ROUND: "iasd-round",
    JA: "ja",
    KIDS: "kids",
    LITURGY: "liturgy",
    LJA_COLOR: "lja-color",
    NT: "nt",
  },
};
