import type { FunctionalComponent, SVGAttributes } from "vue";
import {
  IconAccessible,
  IconAdjustmentsHorizontal,
  IconAlarm,
  IconAlbum,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangleFilled,
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconApi,
  IconArrowBackUp,
  IconArrowBarRight,
  IconArrowBigLeft,
  IconArrowBigRight,
  IconArrowDown,
  IconArrowDownLeft,
  IconArrowDownRight,
  IconArrowForwardUp,
  IconArrowLeft,
  IconArrowMerge,
  IconArrowsExchange,
  IconArrowsShuffle,
  IconAspectRatio,
  IconAtom,
  IconBible,
  IconBlur,
  IconBolt,
  IconBook,
  IconBook2,
  IconBookmarkFilled,
  IconBooks,
  IconBraces,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandWhatsapp,
  IconBrandX,
  IconBrandYoutube,
  IconBucketDroplet,
  IconBug,
  IconBuildingChurch,
  IconCalendar,
  IconCalendarCheck,
  IconCalendarClock,
  IconCalendarFilled,
  IconCalendarStar,
  IconCalendarWeek,
  IconCamera,
  IconCameraFilled,
  IconCandle,
  IconCaretDownFilled,
  IconCaretLeftFilled,
  IconCast,
  IconChalkboard,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronLeftPipe,
  IconChevronRight,
  IconChevronRightPipe,
  IconChevronUp,
  IconCircle,
  IconCircleArrowDownFilled,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleDot,
  IconCirclePlus,
  IconCircleXFilled,
  IconClearAll,
  IconClef,
  IconClock,
  IconClock24,
  IconClockPlay,
  IconClockStop,
  IconCloudDataConnection,
  IconCloudDownload,
  IconCodeDots,
  IconConfetti,
  IconCopy,
  IconCopyCheck,
  IconCopyPlus,
  IconCursorText,
  IconDatabase,
  IconDatabaseImport,
  IconDatabaseMinus,
  IconDeviceDesktop,
  IconDeviceDesktopAnalytics,
  IconDeviceDesktopDown,
  IconDeviceDesktopOff,
  IconDeviceFloppy,
  IconDeviceImac,
  IconDeviceRemote,
  IconDeviceSpeaker,
  IconDeviceTv,
  IconDevices,
  IconDice,
  IconDice5,
  IconDisc,
  IconDiscFilled,
  IconDotsVertical,
  IconDownload,
  IconEraser,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileExport,
  IconFileImport,
  IconFileMusic,
  IconFileMusicFilled,
  IconFilePencil,
  IconFilePlus,
  IconFileSearch,
  IconFileSettings,
  IconFileText,
  IconFileTypePdf,
  IconFiles,
  IconFilter,
  IconFolder,
  IconFolderHeart,
  IconFolderOff,
  IconFolderOpen,
  IconFolderSearch,
  IconFolders,
  IconGripVertical,
  IconHandLoveYou,
  IconHandOff,
  IconHandTwoFingers,
  IconHeartHandshake,
  IconHelpCircle,
  IconHighlight,
  IconHistory,
  IconHourglass,
  IconHourglassLow,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconKeyboard,
  IconKeyframes,
  IconLanguage,
  IconLayersOff,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLayoutGridFilled,
  IconLeaf,
  IconLibrary,
  IconLibraryPhoto,
  IconLineHeight,
  IconLink,
  IconList,
  IconListCheck,
  IconListNumbers,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMailFilled,
  IconMan,
  IconMaximize,
  IconMenu2,
  IconMessage2,
  IconMessageReport,
  IconMicrophone2,
  IconMinimize,
  IconMinus,
  IconMoodHappy,
  IconMoodSad,
  IconMoon,
  IconMovie,
  IconMusic,
  IconMusicOff,
  IconMusicPlus,
  IconNetwork,
  IconNews,
  IconNotes,
  IconNumber123,
  IconPalette,
  IconPaletteFilled,
  IconPencil,
  IconPencilFilled,
  IconPhoto,
  IconPhotoEdit,
  IconPhotoMinus,
  IconPhotoOff,
  IconPhotoPlus,
  IconPiano,
  IconPilcrow,
  IconPlayerPauseFilled,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconPlaylist,
  IconPlaylistAdd,
  IconPlaylistFilled,
  IconPlaylistX,
  IconPlugOff,
  IconPlus,
  IconPointFilled,
  IconPower,
  IconPresentation,
  IconPresentationFilled,
  IconProgressDown,
  IconPuzzle,
  IconQrcode,
  IconQuote,
  IconRefresh,
  IconRepeat,
  IconRepeatOff,
  IconRestore,
  IconRewindBackward10,
  IconRewindForward10,
  IconRotateClockwise,
  IconScreenShare,
  IconScript,
  IconSearch,
  IconSectionSign,
  IconSend,
  IconSeparatorHorizontal,
  IconServer,
  IconSettings,
  IconSettingsFilled,
  IconSlideshow,
  IconSpeakerphone,
  IconSquare,
  IconSquareCheckFilled,
  IconSquareMinus,
  IconSquarePlus,
  IconSquares,
  IconStack2,
  IconStack3,
  IconStar,
  IconStarFilled,
  IconStarOff,
  IconStopwatch,
  IconSun,
  IconSunMoon,
  IconTag,
  IconTerminal2,
  IconTools,
  IconTransfer,
  IconTransitionRight,
  IconTrash,
  IconTrashFilled,
  IconTrophy,
  IconUpload,
  IconUser,
  IconUserHeart,
  IconUserShield,
  IconUsers,
  IconVideo,
  IconVideoFilled,
  IconVideoPlus,
  IconVinyl,
  IconVolume,
  IconVolume2,
  IconVolume3,
  IconVolume4,
  IconWallpaper,
  IconWallpaperOff,
  IconWifi,
  IconWifiOff,
  IconWindowMaximize,
  IconWorld,
  IconX,
  IconYoga,
} from "@tabler/icons-vue";

/**
 * Registro dos ícones de interface, e a única porta de entrada deles.
 *
 * O desenho vem do pacote, não de arquivo no repositório: acervo copiado
 * congela na versão do dia da cópia e convida cada um a soltar o próprio SVG
 * ao lado. Só as marcas do projeto — que o Tabler não tem — seguem como
 * arquivo, em `src/assets/icons/`.
 *
 * Os imports são nomeados de propósito. Resolver por nome a partir de
 * `import * as` arrastaria os 6250 ícones do pacote para o bundle; assim entra
 * só o que está listado aqui.
 *
 * Ícone novo entra em três passos: `ICONS.*` em `src/config/Icons.ts`, o import
 * e a entrada abaixo. `Icons.spec.ts` falha enquanto faltar qualquer um.
 */
export const TABLER_ICONS: Record<string, FunctionalComponent<SVGAttributes>> = {
  accessible: IconAccessible,
  "adjustments-horizontal": IconAdjustmentsHorizontal,
  alarm: IconAlarm,
  album: IconAlbum,
  "alert-circle": IconAlertCircle,
  "alert-circle-filled": IconAlertCircleFilled,
  "alert-triangle-filled": IconAlertTriangleFilled,
  "align-center": IconAlignCenter,
  "align-left": IconAlignLeft,
  "align-right": IconAlignRight,
  api: IconApi,
  "arrow-back-up": IconArrowBackUp,
  "arrow-bar-right": IconArrowBarRight,
  "arrow-big-left": IconArrowBigLeft,
  "arrow-big-right": IconArrowBigRight,
  "arrow-down": IconArrowDown,
  "arrow-down-left": IconArrowDownLeft,
  "arrow-down-right": IconArrowDownRight,
  "arrow-forward-up": IconArrowForwardUp,
  "arrow-left": IconArrowLeft,
  "arrow-merge": IconArrowMerge,
  "arrows-exchange": IconArrowsExchange,
  "arrows-shuffle": IconArrowsShuffle,
  "aspect-ratio": IconAspectRatio,
  atom: IconAtom,
  bible: IconBible,
  blur: IconBlur,
  bolt: IconBolt,
  book: IconBook,
  "book-2": IconBook2,
  "bookmark-filled": IconBookmarkFilled,
  books: IconBooks,
  braces: IconBraces,
  "brand-facebook": IconBrandFacebook,
  "brand-github": IconBrandGithub,
  "brand-instagram": IconBrandInstagram,
  "brand-linkedin": IconBrandLinkedin,
  "brand-whatsapp": IconBrandWhatsapp,
  "brand-x": IconBrandX,
  "brand-youtube": IconBrandYoutube,
  "bucket-droplet": IconBucketDroplet,
  bug: IconBug,
  "building-church": IconBuildingChurch,
  calendar: IconCalendar,
  "calendar-check": IconCalendarCheck,
  "calendar-clock": IconCalendarClock,
  "calendar-filled": IconCalendarFilled,
  "calendar-star": IconCalendarStar,
  "calendar-week": IconCalendarWeek,
  camera: IconCamera,
  "camera-filled": IconCameraFilled,
  candle: IconCandle,
  "caret-down-filled": IconCaretDownFilled,
  "caret-left-filled": IconCaretLeftFilled,
  cast: IconCast,
  chalkboard: IconChalkboard,
  "chart-bar": IconChartBar,
  check: IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-left-pipe": IconChevronLeftPipe,
  "chevron-right": IconChevronRight,
  "chevron-right-pipe": IconChevronRightPipe,
  "chevron-up": IconChevronUp,
  circle: IconCircle,
  "circle-arrow-down-filled": IconCircleArrowDownFilled,
  "circle-check": IconCircleCheck,
  "circle-check-filled": IconCircleCheckFilled,
  "circle-dot": IconCircleDot,
  "circle-plus": IconCirclePlus,
  "circle-x-filled": IconCircleXFilled,
  "clear-all": IconClearAll,
  clef: IconClef,
  clock: IconClock,
  "clock-24": IconClock24,
  "clock-play": IconClockPlay,
  "clock-stop": IconClockStop,
  "cloud-data-connection": IconCloudDataConnection,
  "cloud-download": IconCloudDownload,
  "code-dots": IconCodeDots,
  confetti: IconConfetti,
  copy: IconCopy,
  "copy-check": IconCopyCheck,
  "copy-plus": IconCopyPlus,
  "cursor-text": IconCursorText,
  database: IconDatabase,
  "database-import": IconDatabaseImport,
  "database-minus": IconDatabaseMinus,
  "device-desktop": IconDeviceDesktop,
  "device-desktop-analytics": IconDeviceDesktopAnalytics,
  "device-desktop-down": IconDeviceDesktopDown,
  "device-desktop-off": IconDeviceDesktopOff,
  "device-floppy": IconDeviceFloppy,
  "device-imac": IconDeviceImac,
  "device-remote": IconDeviceRemote,
  "device-speaker": IconDeviceSpeaker,
  "device-tv": IconDeviceTv,
  devices: IconDevices,
  dice: IconDice,
  "dice-5": IconDice5,
  disc: IconDisc,
  "disc-filled": IconDiscFilled,
  "dots-vertical": IconDotsVertical,
  download: IconDownload,
  eraser: IconEraser,
  "external-link": IconExternalLink,
  eye: IconEye,
  "eye-off": IconEyeOff,
  file: IconFile,
  "file-export": IconFileExport,
  "file-import": IconFileImport,
  "file-music": IconFileMusic,
  "file-music-filled": IconFileMusicFilled,
  "file-pencil": IconFilePencil,
  "file-plus": IconFilePlus,
  "file-search": IconFileSearch,
  "file-settings": IconFileSettings,
  "file-text": IconFileText,
  "file-type-pdf": IconFileTypePdf,
  files: IconFiles,
  filter: IconFilter,
  folder: IconFolder,
  "folder-heart": IconFolderHeart,
  "folder-off": IconFolderOff,
  "folder-open": IconFolderOpen,
  "folder-search": IconFolderSearch,
  folders: IconFolders,
  "grip-vertical": IconGripVertical,
  "hand-love-you": IconHandLoveYou,
  "hand-off": IconHandOff,
  "hand-two-fingers": IconHandTwoFingers,
  "heart-handshake": IconHeartHandshake,
  "help-circle": IconHelpCircle,
  highlight: IconHighlight,
  history: IconHistory,
  hourglass: IconHourglass,
  "hourglass-low": IconHourglassLow,
  "info-circle": IconInfoCircle,
  "info-circle-filled": IconInfoCircleFilled,
  keyboard: IconKeyboard,
  keyframes: IconKeyframes,
  language: IconLanguage,
  "layers-off": IconLayersOff,
  "layout-dashboard": IconLayoutDashboard,
  "layout-grid": IconLayoutGrid,
  "layout-grid-filled": IconLayoutGridFilled,
  leaf: IconLeaf,
  library: IconLibrary,
  "library-photo": IconLibraryPhoto,
  "line-height": IconLineHeight,
  link: IconLink,
  list: IconList,
  "list-check": IconListCheck,
  "list-numbers": IconListNumbers,
  lock: IconLock,
  "lock-open": IconLockOpen,
  mail: IconMail,
  "mail-filled": IconMailFilled,
  man: IconMan,
  maximize: IconMaximize,
  "menu-2": IconMenu2,
  "message-2": IconMessage2,
  "message-report": IconMessageReport,
  "microphone-2": IconMicrophone2,
  minimize: IconMinimize,
  minus: IconMinus,
  "mood-happy": IconMoodHappy,
  "mood-sad": IconMoodSad,
  moon: IconMoon,
  movie: IconMovie,
  music: IconMusic,
  "music-off": IconMusicOff,
  "music-plus": IconMusicPlus,
  network: IconNetwork,
  news: IconNews,
  notes: IconNotes,
  "number-123": IconNumber123,
  palette: IconPalette,
  "palette-filled": IconPaletteFilled,
  pencil: IconPencil,
  "pencil-filled": IconPencilFilled,
  photo: IconPhoto,
  "photo-edit": IconPhotoEdit,
  "photo-minus": IconPhotoMinus,
  "photo-off": IconPhotoOff,
  "photo-plus": IconPhotoPlus,
  piano: IconPiano,
  pilcrow: IconPilcrow,
  "player-pause-filled": IconPlayerPauseFilled,
  "player-play": IconPlayerPlay,
  "player-play-filled": IconPlayerPlayFilled,
  "player-skip-back": IconPlayerSkipBack,
  "player-skip-forward": IconPlayerSkipForward,
  "player-stop": IconPlayerStop,
  "player-stop-filled": IconPlayerStopFilled,
  "player-track-next": IconPlayerTrackNext,
  "player-track-prev": IconPlayerTrackPrev,
  playlist: IconPlaylist,
  "playlist-add": IconPlaylistAdd,
  "playlist-filled": IconPlaylistFilled,
  "playlist-x": IconPlaylistX,
  "plug-off": IconPlugOff,
  plus: IconPlus,
  "point-filled": IconPointFilled,
  power: IconPower,
  presentation: IconPresentation,
  "presentation-filled": IconPresentationFilled,
  "progress-down": IconProgressDown,
  puzzle: IconPuzzle,
  qrcode: IconQrcode,
  quote: IconQuote,
  refresh: IconRefresh,
  repeat: IconRepeat,
  "repeat-off": IconRepeatOff,
  restore: IconRestore,
  "rewind-backward-10": IconRewindBackward10,
  "rewind-forward-10": IconRewindForward10,
  "rotate-clockwise": IconRotateClockwise,
  "screen-share": IconScreenShare,
  script: IconScript,
  search: IconSearch,
  "section-sign": IconSectionSign,
  send: IconSend,
  "separator-horizontal": IconSeparatorHorizontal,
  server: IconServer,
  settings: IconSettings,
  "settings-filled": IconSettingsFilled,
  slideshow: IconSlideshow,
  speakerphone: IconSpeakerphone,
  square: IconSquare,
  "square-check-filled": IconSquareCheckFilled,
  "square-minus": IconSquareMinus,
  "square-plus": IconSquarePlus,
  squares: IconSquares,
  "stack-2": IconStack2,
  "stack-3": IconStack3,
  star: IconStar,
  "star-filled": IconStarFilled,
  "star-off": IconStarOff,
  stopwatch: IconStopwatch,
  sun: IconSun,
  "sun-moon": IconSunMoon,
  tag: IconTag,
  tools: IconTools,
  transfer: IconTransfer,
  "terminal-2": IconTerminal2,
  "transition-right": IconTransitionRight,
  trash: IconTrash,
  "trash-filled": IconTrashFilled,
  trophy: IconTrophy,
  upload: IconUpload,
  user: IconUser,
  "user-heart": IconUserHeart,
  "user-shield": IconUserShield,
  users: IconUsers,
  video: IconVideo,
  "video-filled": IconVideoFilled,
  "video-plus": IconVideoPlus,
  vinyl: IconVinyl,
  volume: IconVolume,
  "volume-2": IconVolume2,
  "volume-3": IconVolume3,
  "volume-4": IconVolume4,
  wallpaper: IconWallpaper,
  "wallpaper-off": IconWallpaperOff,
  wifi: IconWifi,
  "wifi-off": IconWifiOff,
  "window-maximize": IconWindowMaximize,
  world: IconWorld,
  x: IconX,
  yoga: IconYoga,
};
